name: weighted_random_picker
description: The elements of the array given to the constructor can be randomly picked with weights according to the probabilityWeight property of each element.
version: 1.0.0
homepage: https://github.com/malt03/weighted_random_picker

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  coverage: ^1.6.1
